title: eggmobile.jp
description: 制作物のアーカイブ
theme: minima
timezone: Asia/Tokyo
permalink: /:year/:month/:day/:title/
instagram_username: eggmobile
twitter_username: eggmobile
github_username: eggmobile
header_pages:
  - exhibitions/index.md
  - devices/index.md
  - sneakers/index.md
  - apparel/index.md
  - apps/index.md
  - contact/index.md
